name: Discord Alert

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\":\":bell: Novo commit no branch main!\nAutor: $AUTHOR\nMensagem: $COMMIT_MESSAGE\"}" \
            $DISCORD_WEBHOOK_URL